# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

#group: deprecated-2017Q2
language: generic
sudo: required
#sudo: false
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.6.4

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.6.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.6.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.6.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./travis.install.py

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./.travis.install.py

script:
  - lazbuild $LAZ_OPT ./HashLib.Tests/FreePascal.Tests/HashLib.Tests.lpi               # Build HashLib4Pascal Test Project
  - $LAZ_ENV ./bin/HashLib.Tests --all --format=plain # Run HashLib4Pascal TestSuite

notifications:
  email:
    on_success: false
    on_failure: change